logging:
  level:
    root: DEBUG
  file:
    name: dmdev.log
    path: /
spring:
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/bi_reports
    username: postgres
    password: NVolga21
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

  messages:
    basename: messages